### ISSUE TITLE
milb_batter_game_logs_fg - returning a couple of different errors.

### ISSUE THREAD

**Issue by jpurrutia** [BillPetti/baseballr#166]
`library(baseballr)
library(tidyr)

df = read.csv('id_vector.csv')
test = list()

for (i in 1:nrow(df)) {
    test[[i]] = milb_batter_game_logs_fg(playerid=df$fangraph_minor_id[i],year=df$year[i])
}
`
I'm trying to run this against this CSV and there are a couple of different errors. It iterates a some rounds before it breaks.

1. > rlang::last_error()
<error/dplyr_error>
Problem with `mutate()` input `name`.
x Input `name` can't be recycled to size 105.
ℹ Input `name` is `player_name`.
ℹ Input `name` must be size 105 or 1, not 0.

2. > rlang::last_error()
<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'Date' not found
ℹ Input `..1` is `!grepl("Date|Total", Date)`.

Here's the csv:
[id_vector.csv.zip](https://github.com/BillPetti/baseballr/files/4904409/id_vector.csv.zip)

My guess is that it's on fangraphs' end, but I'm not completely sure.

**Comment by BillPetti** [comment]
So, if you are really looping over ~20,000 requests, this appears to be due to your ip address getting temporarily banned by the site due to the high volume of requests. That's way too many. I was able to reproduce the error after about 40 and that's even with some random sleep built in. If this is really something you want to do (and I don't know that it's in the best spirit of how the site has been supportive of this package) I'd say you need to break this up over the course of a week or weeks and only query a reasonable amount per day. You will likely need to manually visit the site to prove you are a human to get your ip block lifted, unless it is a time-based block (which I don't know).

**Comment by jpurrutia** [comment]
Bill thank you for that info. That makes sense.
