### ISSUE TITLE
scrape_statcast_savant: Columns are mistakenly combined (I think), leading to shifted rows and incorrect values

### ISSUE THREAD

**Issue by anguspmitchell** [BillPetti/baseballr#195]
For March 26th, there is an NA `pitch_number`, even though that field is populated in the raw CSV

### baseballr value
```R
remove.packages("baseballr")
devtools::install_github("https://github.com/BillPetti/baseballr", ref="21b4b7f12ea1353e23bb225c5585e8419ee1d6a1") # commit from morning of Thu April 1: "added magrittr to imports"
result = baseballr::scrape_statcast_savant('2021-03-26', '2021-03-26')
result[is.na(result$pitch_number),]
```

### Raw CSV value
https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C&hfC&hfSea=2021%7C&hfSit=&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&player_type=batter&hfInfield=&team=&position=&hfOutfield=&hfRO=&home_road=&game_date_gt=2021-03-26&game_date_lt=2021-03-26&hfFlag=&hfPull=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details

### Screenshot of difference
It won't let me upload a CSV unfortunately. 

![Screenshot from 2021-04-02 01-06-08](https://user-images.githubusercontent.com/4749149/113386331-a67f6b80-934f-11eb-967c-ee2088028fc8.png)

@BillPetti Happy to shoot you more info in an email if that helps. Or look into a fix if you don't have time. Would love to get this sorted out as soon as possible. Thanks!

**Comment by BillPetti** [comment]
I'm seeing the same issue with both baseballr and the direct download. Here are the number of `plate_x`fields that are `NA` by `game_pk`:

<img width="359" alt="Screen Shot 2021-04-02 at 7 49 42 AM" src="https://user-images.githubusercontent.com/1923057/113413198-0db91200-9388-11eb-8ea6-8812aa06c425.png">

Since this was Sprint Training it appears to be an issue with those parks/games?

I'm also not seeing that exact row replicated when I download from Savant through baseballr.

**Comment by anguspmitchell** [comment]
I can't reproduce it either now. I just reran the same snippet and it's returning 0 rows now instead of 1. They must have fixed something on their end overnight? Thanks for investigating.

**Comment by BillPetti** [comment]
No worries, it's that time of the year!
