### ISSUE TITLE
Some players' data is not coming through

### ISSUE THREAD

**Issue by ZebraAvatar** [BillPetti/baseballr#227]
**Describe the bug**
When I attempt to pull game logs for certain players, I get an error and cannot retrieve anything.

**To Reproduce**
`pitcher_game_logs_fg(19427, 2021)`

![image](https://user-images.githubusercontent.com/73256571/139627040-9858ca6f-e1dd-498b-bba5-6977e0b518ec.png)

**Desktop:**
 - OS: Windows 11
 - baseballr_0.9.91
 - R version 4.0.5 (2021-03-31)
 - R Studio Version 1.4.1106

**Additional context**
I do not get this error when I run it on a different computer using baseballr_0.8.4 on Windows 10, also using R 4.0.5.

**Comment by kbrownianmotion** [comment]
I looked into the function and noticed a problem with the table's CSS selector. `rvest::html_nodes("table"))[16] ` selects the 16th element out of a node et designated by the `table` selector. But for some player pages, the table's location within that nodeset isn't always the 16th element. In the example you provide, it's the 17th element, which is why you're seeing the error.

Replacing that chunk of code with something that uses a more specific CSS selector does the trick:

```
  payload <- (xml2::read_html(url) %>%
                rvest::html_element(".rgMasterTable")) %>%
    rvest::html_table(fill = TRUE) %>%
    as_tibble(.name_repair = "universal")
```
So the whole function would be:
```
pitcher_game_logs_fg <- function(playerid, year = 2017) {
  
  message('Data courtey of FanGraphs.com. Please consider supporting FanGraphs by purchasing a membership: https://plus.fangraphs.com/product/fangraphs-membership/?switch-subscription=254671&item=85029&_wcsnonce=3e893e9b53&auto-switch=true')
  
  url <- paste0("http://www.fangraphs.com/statsd-legacy.aspx?playerid=",
                playerid,
                "&season=",
                year, "&position=P")

  payload <- (xml2::read_html(url) %>%
                rvest::html_element(".rgMasterTable")) %>%
    rvest::html_table(header = TRUE) %>%
    as_tibble(.name_repair = "universal")
  
  payload <- payload %>%
    dplyr::filter(!grepl("Date|Total", .data$Date)) 
  if (nrow(payload) > 1) {
    suppressWarnings(
      payload <- payload %>% 
        dplyr::mutate(
          K.9 = as.numeric(.data$K.9),
          BB.9 = as.numeric(.data$BB.9),
          HR.9 = as.numeric(.data$HR.9),
          LOB. = as.numeric(gsub("[\\%,]", "", .data$LOB.)),
          GB. = as.numeric(gsub("[\\%,]", "", .data$GB.)),
          HR.FB = as.numeric(gsub("[\\%,]", "", .data$HR.FB))) %>% 
        dplyr::rename(
          K_9 = .data$K.9,
          BB_9 = .data$BB.9,
          HR_9 = .data$HR.9,
          LOB_perc = .data$LOB., 
          GB_perc = .data$GB.,
          HR_FB = .data$HR.FB)
    )
  } else {
    suppressWarnings(
      payload <- lapply(payload, function(x) (as.numeric(gsub("[\\%,]", "", x)))) %>%
        dplyr::bind_rows()
    )
  }
  
  
  payload$LOB_perc <- as.numeric(payload$LOB_perc)/100
  payload$GB_perc <- as.numeric(payload$GB_perc)/100
  
  return(payload)
}
```

This uses `as_tibble(.name_repair = "universal")` to remove the % and / characters from column names. I think it's because rvest::html_table() had been parsing a nodeset with a single element rather than a single node. Unless there's a better way to repair the names, a pipe to `as.data.frame()` would be more consistent with the rest of the package's functions.

The same CSS selector fix can also be applied to `batter_game_logs_fg.R`.

**Comment by saiemgilani** [comment]
Nice. Will do

**Comment by saiemgilani** [comment]
actually, i'm reworking all the fangraphs stuff too. i'm tired of front-end scraping nonsense

**Comment by saiemgilani** [comment]
I this should be fixed and provide an absolute boatload of new additional data as of 0.9.93
