### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by jestarr** [BillPetti/baseballr#23]
The bulk of the package is installing for me, but the full package isn't.  I'm getting error messages at this stage.

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/XML_3.98-1.6.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/XML_3.98-1.6.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/XML_3.98-1.6.tgz': HTTP status was '404 Not Found'
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘XML’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  : 
  subscript out of bounds

**Comment by keberwein** [comment]
What version of R are you using? It doesn't look like the XML package is in the 3.4 directory yet. I would recommend installing the XML package from source. [Download here](https://cran.r-project.org/web/packages/XML/index.html) and `install.packages("path/to/where/you/downloaded/XML/binaries"‌​, type="source")`. Otherwise, you could always roll-back your version of R. I'm running R 3.3 on El Capitan just fine:)

**Comment by jestarr** [comment]
All set now.  Thanks!
