### ISSUE TITLE
Statline From Statcast

### ISSUE THREAD

**Issue by rcarden71** [BillPetti/baseballr#247]
Getting this error message when trying to run this code: statline_from_statcast(Statcast2021, base = "pa") -> Statlines2021

Error in `dplyr::mutate()`:
! Problem while computing `hit_type = dplyr::case_when(...)`.
Caused by error in `` names(message) <- `*vtmp*` ``:
! 'names' attribute [1] must be the same length as the vector [0]
Run `rlang::last_error()` to see where the error occurred.

Package missing, perhaps?

Thanks,

Rob

**Comment by BillPetti** [comment]
The issue is when creating `hit_type` the NA values for the `case_when` statement need to end with `TRUE ~ NA_real_` not `TRUE = TRUE ~ NA_integer_`. (Why I don't know, but that's what fixes the error.)

@saiemgilani Should I fix on `master` and then pull back to `dev`, or is there another way you want to handle given what we are working on right now?

**Comment by rcarden71** [comment]
Made that sub as suggested and now get this:

Error in `dplyr::left_join()`:
! Can't join on `x$year` x `y$year` because of incompatible types.
i `x$year` is of type <character>>.
i `y$year` is of type <integer>>.
Run `rlang::last_error()` to see where the error occurred.

**Comment by saiemgilani** [comment]
Well, I can spot the error there, it is pulling a substring:

```r
statline$year <- as.integer(substr(max(df$game_date),1,4))
```
for all relevant portions
