### ISSUE TITLE
Package installation issue 

### ISSUE THREAD

**Issue by EmilioCMartinez** [BillPetti/baseballr#44]
I am new to using R and am trying to work through this data and mess around and see what I can do, during installation of the package I will get random errors 

Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'

Any tips t clear this up are appreciated, thanks

**Comment by afeierman** [comment]
Emilio,

1. What operating system (Windows, Mac, or Linux) are you using? 

2. Did you make sure to install from github instead of via CRAN?

via github looks like:

`install_packages('devtools')
require(devtools)
install_github("BillPetti/baseballr")
require(baseballr)`

via CRAN looks like:

`install_packages(baseballr)`

**Comment by jev06** [comment]
I've tried to load this package in versions 3.3.1, 3.3.3, and 3.4.2 and keep getting the following error message:
Warning in install.packages :
  package ‘baseballr’ is not available (for R version 3.3.3)

Can anyone help?

Thanks.

**Comment by BillPetti** [comment]
Are trying to install from CRAN? The package is not available there. You need to install from github using the `devtools` package.

**Comment by EmilioCMartinez** [comment]
Thanks for they reply. For some reason a force close of rstudio allowed the
package to install

**Comment by jev06** [comment]
That worked, thank you!  I've never installed a package from devtools.  This is excellent!

**Comment by BillPetti** [comment]
Great, glad you got it working!
